# Generated by Django 4.0.3 on 2022-03-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('rep', 'Sales_rep'), ('admin_staff', 'Sales_admin_staff'), ('admin_super', 'Sales_admin_superuser')], max_length=255),
        ),
    ]
